name: Upload Python Package

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Checkout ğŸ“¦
      uses: actions/checkout@v4
    - name: Setup PDM ğŸ“¦
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: "3.11"
    - name: Build package ğŸ‘·â€â™‚ï¸
      env:
        PDM_IGNORE_SCM_VERSION: ${{ github.ref_name }}
      run: |
        pdm install
        pdm build --no-sdist
    - name: Upload wheels ğŸ‘·â€â™‚ï¸
      uses: actions/upload-artifact@v4
      with:
        name: wheels
        path: dist
  publish:
    runs-on: ubuntu-latest
    needs: [build]
    concurrency: release
    permissions:
      id-token: write
      contents: write
    steps:
    - name: Checkout ğŸ“¦
      uses: actions/checkout@v4
    - name: Download wheels ğŸ‘·â€â™‚ï¸
      uses: actions/download-artifact@v4
      with:
        name: wheels
        path: dist
    - name: Publish to PyPi ğŸš€
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
        packages-dir: dist
        verbose: true
    - name: Publish package distributions to GitHub Releases
      uses: python-semantic-release/upload-to-gh-release@v9.8.8
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
